//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Player Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Input"",
    ""maps"": [
        {
            ""name"": ""Moving"",
            ""id"": ""292beedc-8e74-4e35-94aa-d0a7e4b59b4f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d2879192-fcc0-47d1-87ff-879507ab9ea5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""13364884-9c75-4dd6-a267-9ba5b3d02a77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""c23d6657-5da0-4744-ba52-9dcf5f12d270"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""3e76d44e-5657-4a6b-9074-464b643e31e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scrolled"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fc571462-4914-4f51-8c49-b5ccde7e9ff8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeGravityY"",
                    ""type"": ""Button"",
                    ""id"": ""e20ffecd-3deb-44d3-b46b-fc471f8177fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeGravityX"",
                    ""type"": ""Button"",
                    ""id"": ""bee9ea95-b895-4d9b-9f4c-14c61ac2d318"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeGravityZ"",
                    ""type"": ""Button"",
                    ""id"": ""4cec3ba1-bf32-45b0-9d76-1caffb2e297e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Equip"",
                    ""type"": ""Button"",
                    ""id"": ""566a2ff0-0214-4a80-992c-055261427ddd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""b6a5496d-c468-43ec-96cc-00a11d4a90b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c020ec33-a8ab-4a39-8301-80bbd720718d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56144ebb-0e71-4bed-b427-f287dc8aa6cd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""43f8ea40-368a-46c0-ac4b-18283b96ab4a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""dc4d97ab-0b63-44cb-bb5e-a7dfd7884540"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""64b98850-0947-40ef-b82f-f0b944fde7fe"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""0ea946de-54a0-47a9-b501-6fcfe3b9c512"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""53d74555-669b-416d-87a1-1e6de64b176e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""2cf2616a-8f19-41c5-a01c-cb5ffa762d81"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""01aa9e60-2518-473d-9416-9feefbcbdf3e"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""98249f9d-2a5d-46df-aab6-bb42dc35faa7"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""244359bb-2bc6-40ea-b883-d5f2b66fd187"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""185990b4-14a4-4cb8-8816-93dc42c0240d"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""79288083-7a10-43bb-8445-8e2c0afbaf56"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93982d96-0ecd-4c29-9aed-31e122edc87a"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32759a20-0405-4b6b-aad3-d0a1a549adc8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b8478f6-54f3-4e1d-8156-fa233455f6e3"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5981b4bb-3cea-4aad-a8d2-518b257c7f36"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scrolled"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23273e48-8a6c-4978-b5a4-19e79945c108"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravityY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1100c5c3-342f-4461-b4d4-7e35e37d2120"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravityY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdbc1a7d-ed59-4914-875e-19f2599624c0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravityX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29a34e5-cae6-4d87-aae7-c39eba145100"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravityX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78e95523-dabb-44d7-89bb-ff871f458b12"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravityZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2514e69f-4633-49ff-9165-1ebeb58792e6"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravityZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7601c114-a3c6-4eb9-87e0-1fbf743873aa"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Equip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3571680-466d-40fa-9b8d-31bebd799296"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Equip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66f44b26-0bf6-44f8-91a5-724b7ad4b19b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1db1b9f-83ea-4464-b2d7-4f043b990c5f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Moving
        m_Moving = asset.FindActionMap("Moving", throwIfNotFound: true);
        m_Moving_Move = m_Moving.FindAction("Move", throwIfNotFound: true);
        m_Moving_Jump = m_Moving.FindAction("Jump", throwIfNotFound: true);
        m_Moving_Look = m_Moving.FindAction("Look", throwIfNotFound: true);
        m_Moving_Fire = m_Moving.FindAction("Fire", throwIfNotFound: true);
        m_Moving_Scrolled = m_Moving.FindAction("Scrolled", throwIfNotFound: true);
        m_Moving_ChangeGravityY = m_Moving.FindAction("ChangeGravityY", throwIfNotFound: true);
        m_Moving_ChangeGravityX = m_Moving.FindAction("ChangeGravityX", throwIfNotFound: true);
        m_Moving_ChangeGravityZ = m_Moving.FindAction("ChangeGravityZ", throwIfNotFound: true);
        m_Moving_Equip = m_Moving.FindAction("Equip", throwIfNotFound: true);
        m_Moving_Drop = m_Moving.FindAction("Drop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Moving
    private readonly InputActionMap m_Moving;
    private IMovingActions m_MovingActionsCallbackInterface;
    private readonly InputAction m_Moving_Move;
    private readonly InputAction m_Moving_Jump;
    private readonly InputAction m_Moving_Look;
    private readonly InputAction m_Moving_Fire;
    private readonly InputAction m_Moving_Scrolled;
    private readonly InputAction m_Moving_ChangeGravityY;
    private readonly InputAction m_Moving_ChangeGravityX;
    private readonly InputAction m_Moving_ChangeGravityZ;
    private readonly InputAction m_Moving_Equip;
    private readonly InputAction m_Moving_Drop;
    public struct MovingActions
    {
        private @PlayerInput m_Wrapper;
        public MovingActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Moving_Move;
        public InputAction @Jump => m_Wrapper.m_Moving_Jump;
        public InputAction @Look => m_Wrapper.m_Moving_Look;
        public InputAction @Fire => m_Wrapper.m_Moving_Fire;
        public InputAction @Scrolled => m_Wrapper.m_Moving_Scrolled;
        public InputAction @ChangeGravityY => m_Wrapper.m_Moving_ChangeGravityY;
        public InputAction @ChangeGravityX => m_Wrapper.m_Moving_ChangeGravityX;
        public InputAction @ChangeGravityZ => m_Wrapper.m_Moving_ChangeGravityZ;
        public InputAction @Equip => m_Wrapper.m_Moving_Equip;
        public InputAction @Drop => m_Wrapper.m_Moving_Drop;
        public InputActionMap Get() { return m_Wrapper.m_Moving; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovingActions set) { return set.Get(); }
        public void SetCallbacks(IMovingActions instance)
        {
            if (m_Wrapper.m_MovingActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnJump;
                @Look.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnLook;
                @Fire.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnFire;
                @Scrolled.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnScrolled;
                @Scrolled.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnScrolled;
                @Scrolled.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnScrolled;
                @ChangeGravityY.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityY;
                @ChangeGravityY.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityY;
                @ChangeGravityY.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityY;
                @ChangeGravityX.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityX;
                @ChangeGravityX.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityX;
                @ChangeGravityX.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityX;
                @ChangeGravityZ.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityZ;
                @ChangeGravityZ.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityZ;
                @ChangeGravityZ.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnChangeGravityZ;
                @Equip.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnEquip;
                @Equip.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnEquip;
                @Equip.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnEquip;
                @Drop.started -= m_Wrapper.m_MovingActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_MovingActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_MovingActionsCallbackInterface.OnDrop;
            }
            m_Wrapper.m_MovingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @Scrolled.started += instance.OnScrolled;
                @Scrolled.performed += instance.OnScrolled;
                @Scrolled.canceled += instance.OnScrolled;
                @ChangeGravityY.started += instance.OnChangeGravityY;
                @ChangeGravityY.performed += instance.OnChangeGravityY;
                @ChangeGravityY.canceled += instance.OnChangeGravityY;
                @ChangeGravityX.started += instance.OnChangeGravityX;
                @ChangeGravityX.performed += instance.OnChangeGravityX;
                @ChangeGravityX.canceled += instance.OnChangeGravityX;
                @ChangeGravityZ.started += instance.OnChangeGravityZ;
                @ChangeGravityZ.performed += instance.OnChangeGravityZ;
                @ChangeGravityZ.canceled += instance.OnChangeGravityZ;
                @Equip.started += instance.OnEquip;
                @Equip.performed += instance.OnEquip;
                @Equip.canceled += instance.OnEquip;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
            }
        }
    }
    public MovingActions @Moving => new MovingActions(this);
    public interface IMovingActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnScrolled(InputAction.CallbackContext context);
        void OnChangeGravityY(InputAction.CallbackContext context);
        void OnChangeGravityX(InputAction.CallbackContext context);
        void OnChangeGravityZ(InputAction.CallbackContext context);
        void OnEquip(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
    }
}
